(MAINT) Require beaker first
Some beaker-pe workflows do not "require 'beaker'" before beaker-pe. We should not assume that beaker is already in the environment: since it's a dependency, a simple require statement will take care of this.

Fixes errors like

~~~
NoMethodError: undefined method `register' for Beaker::DSL:Module
~~~